### ISSUE TITLE
Double Input on "My Account" in User settings. 

### ISSUE THREAD

**Issue by Joshykins** [joe27g/Discord-Theme#4]
![0ce11c93c89c41d141f54a47bdb70a36](https://user-images.githubusercontent.com/27947679/53606359-6eedd600-3b6f-11e9-840f-5ce79a407d35.png)

**Comment by twnlink** [comment]
This should be closed now as it has been resolved.

**Comment by joe27g** [comment]
Fixed in 1aba795.
